baseURL = "http://simpleapiworkshop.awsdemo.today/"
languageCode = "en-us"
title = "Build your API in 45 minutes or less!"
theme = "learn"
uglyurls = false
sectionPagesMenu = "main"
relativeURLs = true

pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  description = "Amazon - Build your first CRUD API in 45 minutes or less!"
  author = "Enrico Romani, Amer Grgic, Garry Sollis, Javy de Koning"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = false
